version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    container_name: client-container

  server:
    build:
      context: ./server
    ports:
      - "5009:5009"
    container_name: server-container
